# Generated by Django 4.1.3 on 2022-11-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=7)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
    ]
